CREATE TABLE Roles (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE,
    Description NVARCHAR(255) NULL,
    IsActive BIT NOT NULL DEFAULT(1)
);

CREATE TABLE Clients (
    Id INT IDENTITY PRIMARY KEY,
    CompanyName NVARCHAR(200) NOT NULL,
    VatNumber NVARCHAR(50) NULL,
    TaxCode NVARCHAR(50) NULL,
    ContactName NVARCHAR(150) NOT NULL,
    Email NVARCHAR(200) NOT NULL,
    Phone NVARCHAR(50) NULL,
    Address NVARCHAR(300) NULL,
    City NVARCHAR(100) NULL,
    Notes NVARCHAR(MAX) NULL,
    Status NVARCHAR(20) NOT NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    IsDeleted BIT NOT NULL DEFAULT(0)
);

CREATE TABLE Users (
    Id INT IDENTITY PRIMARY KEY,
    ClientId INT NULL,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(512) NOT NULL,
    FullName NVARCHAR(150) NOT NULL,
    Email NVARCHAR(200) NOT NULL,
    Phone NVARCHAR(50) NULL,
    RoleId INT NOT NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    LastLoginAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    IsDeleted BIT NOT NULL DEFAULT(0),
    CONSTRAINT FK_Users_Clients FOREIGN KEY (ClientId) REFERENCES Clients(Id),
    CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE SubscriptionPlans (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    Description NVARCHAR(500) NULL,
    MaxQrCodes INT NOT NULL,
    AllowDynamicQr BIT NOT NULL,
    AllowTracking BIT NOT NULL,
    MaxMonthlyScans INT NULL,
    MaxUsers INT NULL,
    AllowExport BIT NOT NULL,
    AllowMultiLink BIT NOT NULL,
    AllowCustomBranding BIT NOT NULL,
    Price DECIMAL(10,2) NULL,
    DurationMonths INT NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE ClientSubscriptions (
    Id INT IDENTITY PRIMARY KEY,
    ClientId INT NOT NULL,
    SubscriptionPlanId INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NULL,
    Status NVARCHAR(20) NOT NULL,
    Notes NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ClientSubscriptions_Clients FOREIGN KEY (ClientId) REFERENCES Clients(Id),
    CONSTRAINT FK_ClientSubscriptions_Plans FOREIGN KEY (SubscriptionPlanId) REFERENCES SubscriptionPlans(Id)
);

CREATE TABLE QrCategories (
    Id INT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(500) NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE QrTypes (
    Id INT IDENTITY PRIMARY KEY,
    Code NVARCHAR(50) NOT NULL UNIQUE,
    Name NVARCHAR(120) NOT NULL,
    Description NVARCHAR(500) NULL,
    Category NVARCHAR(100) NOT NULL,
    IsDynamicSupported BIT NOT NULL,
    RequiresDestinationUrl BIT NOT NULL,
    RequiresPayload BIT NOT NULL,
    PayloadSchemaJson NVARCHAR(MAX) NULL,
    SortOrder INT NOT NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE QrCodes (
    Id INT IDENTITY PRIMARY KEY,
    ClientId INT NOT NULL,
    QrTypeId INT NOT NULL,
    CategoryId INT NULL,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(500) NULL,
    IsDynamic BIT NOT NULL,
    ShortCode NVARCHAR(20) NULL UNIQUE,
    DestinationUrl NVARCHAR(1000) NULL,
    PayloadJson NVARCHAR(MAX) NULL,
    GeneratedContent NVARCHAR(2000) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    ExpirationDate DATETIME2 NULL,
    Notes NVARCHAR(MAX) NULL,
    ScanCount INT NOT NULL DEFAULT(0),
    LastScanAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BIT NOT NULL DEFAULT(0),
    CONSTRAINT FK_QrCodes_Clients FOREIGN KEY (ClientId) REFERENCES Clients(Id),
    CONSTRAINT FK_QrCodes_QrTypes FOREIGN KEY (QrTypeId) REFERENCES QrTypes(Id),
    CONSTRAINT FK_QrCodes_Categories FOREIGN KEY (CategoryId) REFERENCES QrCategories(Id)
);

CREATE TABLE QrScans (
    Id BIGINT IDENTITY PRIMARY KEY,
    QrCodeId INT NOT NULL,
    ClientId INT NOT NULL,
    ScanDate DATETIME2 NOT NULL,
    IpAddress NVARCHAR(100) NOT NULL,
    UserAgent NVARCHAR(1000) NOT NULL,
    Referrer NVARCHAR(1000) NULL,
    DeviceInfo NVARCHAR(500) NULL,
    Country NVARCHAR(100) NULL,
    City NVARCHAR(100) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_QrScans_QrCodes FOREIGN KEY (QrCodeId) REFERENCES QrCodes(Id),
    CONSTRAINT FK_QrScans_Clients FOREIGN KEY (ClientId) REFERENCES Clients(Id)
);

CREATE TABLE AuditLogs (
    Id BIGINT IDENTITY PRIMARY KEY,
    UserId INT NULL,
    ClientId INT NULL,
    ActionType NVARCHAR(100) NOT NULL,
    EntityName NVARCHAR(100) NOT NULL,
    EntityId NVARCHAR(100) NOT NULL,
    Details NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
